### PR TITLE
Export annotator comment

### PR DESCRIPTION
**Pull request by CaseyZhang11**
Exporting annotator comment in downloaded file(DOCUMENT_CLASSIFICATION). 

- Create comment class and create_comment function

CSV: 
image

Json:
`[{"id":1,"text":"Hello how are you?","label":["POSITIVE"],"Comments":["hihihihihi","not good, bad"]},{"id":2,"text":"I have a complaint","label":["NEGATIVE"],"Comments":["nonononono"]},{"id":3,"text":"Wanted to check my bill amount","label":["NEGATIVE"],"Comments":["nonononononononoon"]},{"id":4,"text":"I want to cancel my booking.","label":["NEGATIVE"],"Comments":[]},{"id":5,"text":"Hello how are you?","label":["POSITIVE"],"Comments":[]},{"id":6,"text":"I have a complaint","label":["NEGATIVE"],"Comments":[]},{"id":7,"text":"Wanted to check my bill amount","label":["NEGATIVE"],"Comments":[]},{"id":8,"text":"I want to cancel my booking.","label":["NEGATIVE"],"Comments":["Not good"]}]`

FastText:
image

### CODE REVIEW

**Comment by CaseyZhang11** [comment]
#1875

**Comment by CaseyZhang11** [comment]
Example of multi labels and multi comments

image

**Review by Vydruth — APPROVED** [review]
LGTM! 

@Hironsan could you review and merge if you think it looks good?

**Comment by Hironsan** [comment]
I fixed codes to pass isort, black, and flake8 but they still can't pass the tests.

**Comment by CaseyZhang11** [comment]
@Hironsan thanks for checking. I'll update the related test files.

**Comment by CaseyZhang11** [comment]
hey @Hironsan , I just updated the test cases. Btw, does Doccano have an instruction to run the test cases locally?

**Comment by Hironsan** [comment]
The following document will be useful for you:

- https://doccano.github.io/doccano/install_and_upgrade_doccano/#backend

Basically, you need to run the test cases by `poetry run task test`.

**Comment by CaseyZhang11** [comment]
Hey @Hironsan , the local test cases are passed locally. Could you review it again? Thanks

FastText format:
image

**Comment by CaseyZhang11** [comment]
Hey @Hironsan , sorry about pinging you again. Would you mind reviewing this PR? Thanks

**Comment by Hironsan** [comment]
OK. I'll check it soon.

**Comment by Hironsan** [comment]
Resolved conflicts, apply linters, and add a migration file for the `ExportedComment` model. But it still fails tests.

**Comment by CaseyZhang11** [comment]
> Resolved conflicts, apply linters, and add a migration file for the `ExportedComment` model. But it still fails tests.

Hey @Hironsan , the failed tests are related to newly merged commit [d734222](https://github.com/doccano/doccano/pull/1897/commits/d7342222a70c9b6ad250ac060353ba8152b55db8) from master which is the `ExportedBoundingBox` and `ExportedSegmentation`. I can update the test cases for these new methods

**Comment by Hironsan** [comment]
> Hey @Hironsan , the failed tests are related to newly merged commit [d734222](https://github.com/doccano/doccano/pull/1897/commits/d7342222a70c9b6ad250ac060353ba8152b55db8) from master which is the ExportedBoundingBox and ExportedSegmentation. I can update the test cases for these new methods

OK. Please do it.

**Comment by CaseyZhang11** [comment]
Hey @Hironsan , the test cases are updated. Please check again.

**Comment by Hironsan** [comment]
Merged. Thank you for the great work.

**Pull request merged**
