### PR TITLE
fix empty export in entity-relationship-labeling

### LINKED ISSUE #1763: Empty export of entity-relation-labeling
How to reproduce the behaviour
---------
- Project - Create - Sequence Labeling
- check `Allow overlapping entity`, `Use relation labeling`, `Count grapheme clusters as one character`, `Share annotations across all users`
- then import data and do some labeling, then export, without checking `Export only approved documents`. export shows empty result as below
```json
{"id": 4, "text": "Terrible customer service.", "relations": [], "entities": []}
```
Your Environment
---------

*   Operating System: wsl2+ubuntu20.04
*   Python Version Used: 3.8, 3.10
*   When you install doccano: 3 hours ago
*   How did you install doccano (Heroku button etc): first-time pip, then from source code

### PR DESCRIPTION
**Pull request by mkmark**
fix #1763

### CODE REVIEW

**Comment by Hironsan** [comment]
Please pass flake8, black, isort, mypy, and test.

**Comment by mkmark** [comment]
> Please pass flake8, black, isort, mypy, and test.

Just fixed one error per flake8. I wonder if there's a quick note on how I can test `flake8, black, isort, mypy, and test` locally?

**Comment by yinzhiweigithub** [comment]
> fix #1763

Can you fix your problem and resubmit again? many thanks.

**Review by Paul0M — COMMENTED** [review]
have tried NER, this will lead to export annotated dataset right.

**Comment by Aj-232425** [comment]
Hey @Hironsan  i want to annotate healthcare data, gone through doccano, but for relation feature, i am unable to draw any lines to show relation between two entities, would you mind sharing any image or screenshot to highlight on this issue. I am able to create label for relation, but how can I relate them..
Thanks &regard..

**Pull request merged**
