### PR TITLE
Align dockerized component versions

### PR DESCRIPTION
**Pull request by kuraga**
Try to use Alpine 3.10 base everywhere if possible.

### CODE REVIEW

**Comment by harmw** [comment]
this also introduces a Python bump: `3.6.9-r2` to `3.7.7-r0`

Are we sure this will work with the codebase?

**Comment by kuraga** [comment]
@harmw , hm, I don't.

But now, different Alpines (and packages?) are used: 3.9.6, 3.10, latest (3.12).

**Comment by harmw** [comment]
well, not saying it's a bad thing - just that it's bringing in this rather implicit upgrade of `python` :)

I'm not aware of how good/bad the CI coverage is, but given it managed to build the `app` container and execute tests, I guess we can go forward with this 👍 

I have not verified this for `nodejs` though, same rules apply there. The only really easy container is nginx, as that isn't core to the project and isn't doing anything fancy anyway 🙈

**Comment by kuraga** [comment]
IMHO it's a good time to align/update all dependencies... :smile: (not only main)

**Comment by Hironsan** [comment]
This doen't works when executing `docker-compose -f docker-compose.dev.yml up`.  Maybe bash installation is required in `frontend/Dockerfile`.

```
frontend_1  | env: can't execute 'bash': No such file or directory
```

**Comment by kuraga** [comment]
Strange if _containers_ work different.

But agree, added.

**Comment by Hironsan** [comment]
Thank you for the commit. But it doesn't still work.

Although I said `Maybe bash installation is required in frontend/Dockerfile`, I found it's not correct. Because `frontend/Dockerfile` is not used by `docker-compose.dev.yml`. So it is not necessary to install bach in the Dockerfile. Sorry for the confusion.

Instead of using the Dockerfile, `docker-compose.dev.yml` currently uses `node:13.2-alpine3.10` image directly. The image before this PR uses `node:13.2.0` that contains bash so it is no problem to run `dev-nuxt.sh`. But currently the image is changed to `node:13.2-alpine3.10` that doesn't contain bash. So it fails to run 'dev-nuxt.sh'.

**Comment by kuraga** [comment]
Then #810 influences here... But strange, I don't have error on clean Docker installation.

**Comment by Hironsan** [comment]
Try?
https://github.com/doccano/doccano/blob/master/docs/faq.md#i-want-to-update-to-the-latest-doccano-image

**Comment by kuraga** [comment]
@Hironsan ,
> on clean Docker installation.

**Comment by kuraga** [comment]
I mean, Docker is clean. `/var/lib/docker` cleaned before `docker-compose -f docker-compose.dev.yml up`.

**Comment by kuraga** [comment]
@Hironsan , could you check on clean Docker, please?

**Comment by Hironsan** [comment]
I set up a new instance, installed docker and docker-compose from scratch and ran `docker-compose -f docker-compose.dev.yml`. But the result was the same.

```bash
frontend_1  | env: can't execute 'bash': No such file or directory
doccano_frontend_1 exited with code 127
```

FYI:
- Ubuntu 18.04.4 LTS
- docker-compose version 1.26.1, build f216ddbf
- Docker version 19.03.12, build 48a66213fe

**Comment by kuraga** [comment]
@Hironsan , let's compare hashes?

```
$ sudo rc-service docker status
 * status: stopped

$ git status
На ветке patch-6
Ваша ветка обновлена в соответствии с «origin/patch-6».

нечего коммитить, нет изменений в рабочем каталоге

$ git show-ref patch-6
b6fc26644de93ba8ad980c041323b14986460b9e refs/heads/patch-6
b6fc26644de93ba8ad980c041323b14986460b9e refs/remotes/origin/patch-6

$ sudo rm -rf /var/lib/docker

$ sudo rc-service docker start
docker            | * Starting docker ...       [ ok ]

$ docker-compose -f docker-compose.dev.yml up
<...>

$ docker container ls -a
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                            PORTS               NAMES
f7242db86a34        node:13.2-alpine3.10   "docker-entrypoint.s…"   21 minutes ago      Exited (127) 21 minutes ago                           doccano_frontend_1
8a71537405f3        python:3.6             "/src/app/tools/dev-…"   21 minutes ago      Exited (137) About a minute ago                       doccano_backend_1
758d579eac1d        postgres:12-alpine     "docker-entrypoint.s…"   21 minutes ago      Exited (0) About a minute ago                         doccano_postgres_1

$ docker image ls -a
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
python              3.6                 e0373ff33a19        3 days ago          914MB
postgres            12-alpine           17150f4321a3        7 days ago          157MB
node                13.2-alpine3.10     fac3d6a8e034        7 months ago        106MB

$ docker volume ls
DRIVER              VOLUME NAME
local               doccano_node_modules
local               doccano_postgres_data
local               doccano_venv
```

**Comment by Hironsan** [comment]
It seems to me that your frontend container also exited with status code `127`.

```
$ git status
On branch pull/842
nothing to commit, working tree clean

$ git show
commit b6fc26644de93ba8ad980c041323b14986460b9e (HEAD -> pull/842)
Merge: 07bdef4 4927a01
Author: Alexander Kurakin <kuraga333@mail.ru>
Date:   Mon Jun 29 10:47:31 2020 +0300
    Merge branch 'master' into patch-6
diff --cc frontend/Dockerfile
index 4444545,e68d9dc..cfd3338
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@@ -4,7 -4,7 +4,7 @@@ WORKDIR /ap
  
  COPY . /app/
  
- RUN apk add -U bash git python3 make g++ \
 -RUN apk add -U --no-cache git python3 make g++ \
++RUN apk add -U --no-cache bash git python3 make g++ \
    && npm install -g npm@latest \
    && npm install \
    && npm run build \

$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE

$ docker volume ls
DRIVER              VOLUME NAME

$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

$ docker container ls
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

$ docker-compose -f docker-compose.dev.yml up
...
frontend_1  | env: can't execute 'bash': No such file or directory
doccano_frontend_1 exited with code 127
...

$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
python              3.6                 e0373ff33a19        3 days ago          914MB
postgres            12-alpine           17150f4321a3        7 days ago          157MB
node                13.2-alpine3.10     fac3d6a8e034        7 months ago        106MB

$ docker ps -a
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                        PORTS               NAMES
815920573fa6        node:13.2-alpine3.10   "docker-entrypoint.s…"   3 minutes ago       Exited (127) 3 minutes ago                        doccano_frontend_1
5121f6748bb6        python:3.6             "/src/app/tools/dev-…"   3 minutes ago       Exited (137) 16 seconds ago                       doccano_backend_1
14bff32ee67c        postgres:12-alpine     "docker-entrypoint.s…"   3 minutes ago       Exited (0) 16 seconds ago                         doccano_postgres_1

$ docker volume ls
DRIVER              VOLUME NAME
local               doccano_node_modules
local               doccano_postgres_data
local               doccano_venv
```

**Comment by kuraga** [comment]
> It seems to me that your frontend container also exited with status code `127`.

Aha. I thought it (i.e. Docker Compose) should fail this case. But it doesn't without `--abort-on-container-exit` option. (BTW, could we suggest it in start instructions?)

Yes, it does. Now I see. Sorry. I am thinking.

**Comment by kuraga** [comment]
Closed. See #870.

**Pull request closed without merging**
