### PR TITLE
Support nested named entity recognition, relation labeling, RTL language, improve speed and grapheme mode

### PR DESCRIPTION
**Pull request by Hironsan**
## Nested mode

Of course, you are able to annotate text without using nested mode.

## RTL Language

In the case of mixed RTL and LTR Language:

## Grapheme mode

In JavaScript, there is not always a one-to-one relationship between string characters and what a user would call a separate visual "letter". Some symbols are represented by several characters. This can cause issues when you annotate the part of the text in sequence labeling.

For example, emoji characters like "🌷","🎁","💩","😜" and "👍" are represented by two JavaScript characters each (high surrogate and low surrogate). That is,

```javascript
"🌷".length == 2
```

The combined emoji is even longer:

```javascript
"🏳️‍🌈".length == 6
```

Therefore, If your text includes such characters, the start/end offset indicates codepoint offset which is different from a "visual offset".

So, I implemented the "Grapheme mode" which counts the character per grapheme cluster. As an example, let's say you select the text as follows:

image

With the grapheme mode, the offset is `(1, 3)`. On the other hand, without the mode, the offset is `(4, 12)` because it counts the codepoints.

## Large Document

I introduced the virtual rendering system to handle a large document. Now, we are able to annotate it(I tested about 1,000,000 characters document).

### CODE REVIEW

**Comment by Hironsan** [comment]
closes #544

**Comment by kris927b** [comment]
> Hi, I use this 1.5.0 version, the relation labeling is not working in sequence labeling. And also creation of relation is not working. Could anyone check the issue?

I have the same issue when using the production docker-compose version. What could be causing this issue?

**Comment by Hironsan** [comment]
I have a plan to extract relation labeling as an independent task. So this PR doesn't include a relation labeling feature.

Status: I'd like to implement that feature, but I haven't gotten around to it because I'm fixing other bugs.

**Comment by zhouao0314** [comment]
Hello @Hironsan , we are trying to use this version, but we need to use the relationship tag function. When will this function be merged?

**Comment by zhouao0314** [comment]
Hello, @Hironsan, we are trying to use this version, but we need to use the relationship tag function. When will this function be merged?

**Comment by anyi3c** [comment]
Hi, @Hironsan, we are trying to use this version, but we need to use the relationship Labeling function. When will this function be merged?

**Comment by Srikanthv466** [comment]
I would like to annotated same entity with multiple labels, so how do we setup nested mode?

**Comment by PeterPanUnderhill** [comment]
Is there an approximate time we can expect? thx

**Comment by PeterPanUnderhill** [comment]
> Is there an approximate time we can expect? thx

@Hironsan

**Comment by fernandrez-ai** [comment]
@Hironsan how can I use this? Can't find any example on how to use nested mode

**Comment by Hironsan** [comment]
Please select "Allow overlapping spans" on creating a sequence labeling project.

**Pull request merged**
