### PR TITLE
Add API document generator

### LINKED ISSUE #299: Any documentation about using as REST service
How could use as REST API service. Send raw text and doccano response the parsed data?

### LINKED ISSUE #646: Django Rest Framework api
I know the backend is based on Django Rest Framework. 

how can I auto document for the django framework api of the doccano .

Your Environment
---------

*   Operating System:mac os
*   Python Version Used:3.6
*   When you install doccano:2020.3.24
*   How did you install doccano (Heroku button etc):docker-compose.dev.yml

### PR DESCRIPTION
**Pull request by Hironsan**
Resolves #299, resolves #646

### CODE REVIEW

**Comment by louisguitton** [comment]
Thank you for this 🎉 

image

**Comment by Hironsan** [comment]
Your welcome.

**Comment by tamio96** [comment]
I realized that new version couldn't access this swagger/ page anymore. Please take a look at this

**Comment by louisguitton** [comment]
> I realized that new version couldn't access this swagger/ page anymore. Please take a look at this

This works @tamio96 let me provide more details.
Checkout the latest master, and run the dev environment:
```sh
docker-compose -f docker-compose.dev.yml up
```
then it starts running on localhost:3000
Go to localhost:8000, authenticate with `admin` and `password` and open http://localhost:8000/swagger/ and you will see the docs

**Pull request merged**
