### PR TITLE
Relation labeling with sequence labeling

### LINKED ISSUE #233: Feature Request: Relation Annotation
I see it is on the [roadmap](https://github.com/chakki-works/doccano/blob/master/ROADMAP.md) already, but relation annotation would be a very useful feature for us.

### LINKED ISSUE #1418: How to export labeled relationship ?
I have labeled the entities and relationships between these entities.(Using Sequence Labeling)

However, when exporting the result data, only entities were shown in the JSON, couldn't find any relationships in it.

So I wonder whether this version doesn't support relationship labeling completely or I am not using it correctly?

### LINKED ISSUE #1534: Relation labeling for sequenceLabeling is not working
Used `docker pull doccano/doccano ` to install the latest version, but after installation, the relation labeling for sequenceLabeling is not working, don't see the 'R' icon on the labeled entity, also i'm not able to create relation at all.

### LINKED ISSUE #1559: Sequence Labeling with relationship linking
How to reproduce the behaviour
---------
I wasnt able to achieve entity linking with the Sequence Labeling method, as shown in the demo.
How do we achieve this with Doccano ?

Example : 
{"text": "Before launching V-Bio Ventures, Christina was a partner at Forbion Capital Partners (previously ABN AMRO Capital) were she led and managed a series of successful investments in biopharmaceutical and pharmaceutical companies.", "label": [ [17, 31, "ORG"],[60,84,"ORG"],[97,113,"ORG"] ], "relation": [[ "V-Bio Ventures"," Christina was a partner at ", "Forbion Capital Partners"],["V-Bio Ventures"," Christina was a partner at Forbion Capital Partners (previously ","ABN AMRO Capital"],["Forbion Capital Partners", "(previously ", "ABN AMRO Capital"]]}

Using Docker to setup Doccano.

### LINKED ISSUE #1593: failed to add new relations by docker
docker image:
doccano/doccano                              latest
docker version:
20.10.10

system:
Linux floyd-ubt 5.13.0-16-generic #16-Ubuntu SMP Fri Sep 3 14:53:27 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Just get nothing when i intend to add a new relation.Here is the screen snapshot
======
image
image

### PR DESCRIPTION
**Pull request by Hironsan**
## UI

image

## Export format

```
{
    "id": 0,
    "text": "Google was founded on September 4, 1998, by Larry Page and Sergey Brin.",
    "entities": [
        {
            "id": 0,
            "start_offset": 0,
            "end_offset": 6,
            "label": "ORG"
        },
        {
            "id": 1,
            "start_offset": 22,
            "end_offset": 39,
            "label": "DATE"
        },
        {
            "id": 2,
            "start_offset": 44,
            "end_offset": 54,
            "label": "PERSON"
        },
        {
            "id": 3,
            "start_offset": 59,
            "end_offset": 70,
            "label": "PERSON"
        }
    ],
    "relations": [
        {
            "id": 0,
            "from_id": 0,
            "to_id": 1,
            "type": "foundedAt"
        },
        {
            "id": 1,
            "from_id": 0,
            "to_id": 2,
            "type": "foundedBy"
        },
        {
            "id": 2,
            "from_id": 0,
            "to_id": 3,
            "type": "foundedBy"
        }
    ]
}
```

fix #1593 
fix #1534 
fix #1559
fix #233 
fix #1418

### CODE REVIEW

**Comment by jayaddison** [comment]
Thank you, @Hironsan !

**Comment by Hironsan** [comment]
Your welcome. If there are any problems or improvement ideas, please let me know.

**Comment by elexira** [comment]
Hello we have pulled the latest images from dockerhub. We have some data annotated that already contains relationships. We tried many different ways to import this data to doccano to visually show them to others, but we do not know how to import annotated data with relationships to doccano. The exported data format is not supported when importing data.

**Comment by Hironsan** [comment]
Hello @elexira 

Currently, importing the relation data has not been supported yet.
If you have the format you want to support, please comment it or make an issue.

**Comment by elexira** [comment]
@Hironsan Thank you, it makes sense for the import format to follow the same one that Doccano export format. An example of such format template was provided by you at the top of this very page.

**Comment by PeterPanUnderhill** [comment]
Hi Hironsan, thanks for this amazing project! Is there a time we can expect for the relation labeling/extraction feature? Many thanks!!!

**Comment by Aj-232425** [comment]
Hi @Hironsan i am unable to do relation draw between two entities, could you please share any tutorial or small video, that will help out. Yes, able to do labelling but not relation marking.

**Pull request merged**
