### PR TITLE
Export label text and username instead of ID

### PR DESCRIPTION
**Pull request by lasp73**
This is related to #295

I am submitting this pull request to share a change I did to export label names and user names instead of their IDs.
My focus was text classification, but I have also adjusted sequence classification also (json format).

I am not really a Vue/JS developer (I am more a Java/Python/NLP guy) , so maybe the code is not in the best way.
But... maybe this PR helps to make a final solution.

Thanks

### CODE REVIEW

**Comment by kuraga** [comment]
Let's keep compatibility and add a field with label, only?

Or at least store both label's I'd and name?

**Comment by lasp73** [comment]
@kuraga Sure, it is a good point. 
"label" and "user" are already used for IDs.
To keep compatibility, we could insert "label_name" and "user_name".
What do you think ?

**Comment by kuraga** [comment]
:+1:

**Comment by lasp73** [comment]
@kuraga With the changes, output will be:

```
{"id": 2, "text": "Test 1 – Sentence 2", "annotations": [{"label": 10, "user": 1, "label_name": "Test1_Label2", "user_name": "admin"}, {"label": 13, "user": 2, "label_name": "Test1_Label5", "user_name": "guest"}], "meta": {}, "annotation_approver": null}
{"id": 3, "text": "Test 1 – Sentence 3", "annotations": [{"label": 11, "user": 1, "label_name": "Test1_Label3", "user_name": "admin"}], "meta": {}, "annotation_approver": null}
```

```
annotation_approver,id,label,label_name,text,user,user_name
,2,10,Test1_Label2,Test 1 – Sentence 2,1,admin
,2,13,Test1_Label5,Test 1 – Sentence 2,2,guest
,3,11,Test1_Label3,Test 1 – Sentence 3,1,admin
,1,9,Test1_Label1,Test 1 – Sentence 1,1,admin
,1,12,Test1_Label4,Test 1 – Sentence 1,2,guest
,1,20,Test1_Label0,Test 1 – Sentence 1,2,guest
```

```
{"id": 301, "text": "Test 1 – Sentence 1", "annotations": [{"label": 21, "start_offset": 0, "end_offset": 6, "user": 1, "label_name": "Entity1", "user_name": "admin"}, {"label": 22, "start_offset": 9, "end_offset": 19, "user": 1, "label_name": "Entity2", "user_name": "admin"}], "meta": {}, "annotation_approver": null}
```

**Comment by kuraga** [comment]
@lasp73 , oh, one more thing. The same for annotation approver?

**Comment by lasp73** [comment]
@kuraga, annotation_approver is already a name in doccano/master

**Comment by kuraga** [comment]
@lasp73 , ok.

IMHO we also have to correct [export examples](https://github.com/doccano/doccano/search?q=terrible&unscoped_q=terrible).

**Comment by lasp73** [comment]
@kuraga, sure, just waiting to have a stable solution first
Thanks

**Comment by lasp73** [comment]
@kuraga, I fixed the examples. 
The checks failed but it seems to be a build issue. Right?

**Pull request closed without merging**
